class_name TownEventType
extends RefCounted

enum Type {
	MARKET_DAY,
	FESTIVAL,
	TOURNAMENT,
	GUILD_MEETING,
	NOBLE_PARTY,
	RELIGIOUS_CEREMONY,
	CRIME_SPREE,
	MERCHANT_CARAVAN,
	ROYAL_VISIT,
	DISASTER,
	CELEBRATION,
	COUNCIL_MEETING,
	WEDDING,
	FUNERAL,
	HARVEST_FESTIVAL,
	WINTER_SOLSTICE,
	SPRING_EQUINOX,
	SUMMER_SOLSTICE,
	AUTUMN_EQUINOX,
	EMERGENCY,
	VISITOR,
	CONSTRUCTION,
	TRADE_DEAL,
	CRIME_WAVE,
	WEATHER_EVENT,
	POLITICAL_EVENT,
	RELIGIOUS_EVENT,
	MILITARY_EVENT
}
