name: CI/CD Pipeline

on:
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  godot-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: MikeSchulze/gdunit4-action@v1
        with:
          godot-version: "4.4.1"
          paths: "res://tests"
          timeout: 10 # Optional: Test timeout in minutes
          version: "latest" # Optional: GdUnit4 version
  test:
    name: Test Suite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python for YAML validation
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install -r requirements.txt

      - name: Validate YAML files with yamllint
        uses: karancode/yamllint-github-action@v2.1.1
        with:
          yamllint_file_or_dir: "data/"
          yamllint_strict: false
          yamllint_config_filepath: ".yamllint"
          yamllint_format: "parsable"
          yamllint_comment: false

  lint:
    name: Lint Suite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: tcort/github-action-markdown-link-check@v1
        # with:
        #     check-modified-files-only: true
