name: Publish Game Release

on:
  push:
    branches: [main]
  workflow_dispatch: # Allow manual triggering

env:
  GODOT_VERSION: 4.4.1
  EXPORT_NAME: idle-adventurer
  PROJECT_PATH: "." # path to `project.godot`

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-22.04 # Use 22.04 with godot 4
    container:
      image: barichello/godot-ci:4.4.1-stable
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv "/root/.local/share/godot/export_templates/${GODOT_VERSION}.stable" \
            "~/.local/share/godot/export_templates/${GODOT_VERSION}.stable"
      - name: Web Build
        run: |
          mkdir -v -p build/web
          EXPORT_DIR="$(readlink -f build)"
          cd "$PROJECT_PATH"
          godot --headless --verbose --export-release "Web" "$EXPORT_DIR/web/index.html"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: build/web
      - name: Install rsync 📚
        run: |
          apt-get update && apt-get install -y rsync
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@6c2d9db40f9296374acc17b90404b6e8864128c8 # v4.7.3
        with:
          branch: "main" # The branch the action should deploy to.
          folder: "build/web" # The folder the action should deploy.
